### ISSUE TITLE
502's from GCP

### ISSUE THREAD

**Issue by mwoods79** [dashbitco/broadway_cloud_pub_sub#102]
Hi 👋 

I am having the same issue as this previous issue: https://github.com/dashbitco/broadway_cloud_pub_sub/issues/55

The fixed seemed to be adding retries to Tesla. 

Tesla and retrying was refactored away when the client changed to Finch: https://github.com/dashbitco/broadway_cloud_pub_sub/pull/66

These 502's are continuously alerting via sentry. Would it be ok to either add retries for 502's back or allow a way to inject my own middleware to the client?

I am happy to make a PR for either. I don't want to just silence the 502's in case there is an actual problem I would want to be alerted.

**Comment by josevalim** [comment]
A PR that adds retries to the codebase is very welcome! Thank you for asking!

**Comment by mwoods79** [comment]
Thank you!
