### ISSUE TITLE
0.6.1 breaks acknowledging messages

### ISSUE THREAD

**Issue by michaelst** [dashbitco/broadway_cloud_pub_sub#53]
The expected payload should look like this 
```
{
    "ackIds": [
        "projects/genesis-block-testing/subscriptions/test-subscription:72"
    ]
}
```
but with the upgrade it is sending the ids as maps
```
{
    "ackIds": [
        {
            "ack_id": "projects/genesis-block-testing/subscriptions/test-subscription:72"
        }
    ]
}
```

**Comment by mcrumm** [comment]
Thank you for the report @michaelst! This should be fixed shortly.

**Comment by mcrumm** [comment]
@michaelst v0.6.2 has been published to hex.pm. Thank you once again for the report :heart:
