### ISSUE TITLE
Solution for GCP PubSub routine 502's

### ISSUE THREAD

**Issue by SophisticaSean** [dashbitco/broadway_cloud_pub_sub#55]
GCP returns a 502 pretty routinely serveral times a day when fetching messages:

```html
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">
  <title>Error 502 (Server Error)!!1</title>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
  ```
  
  The issue is the library always `Logger.errors` it and it can lead to false alerts around this problem. 
  
  I've manually forked and I'm going to try to wrap that block in a retry from the retry library and I've also submitted a ticket to GCP about the issue.
  
  Long term, how do we want to solve this problem? It would be nice to be able to use Tesla middleware for these requests like the Retry middleware.
  
  I'm happy to implement the fix I just want guidance before I do.

**Comment by SophisticaSean** [comment]
![Uploading Screen Shot 2021-03-05 at 2.56.52 PM.png…]()

**Comment by SophisticaSean** [comment]
fixed by #56 (poorly) :)

**Comment by josevalim** [comment]
I would honestly be worried about automatically hiding those. Even if we retried, I think we should log the possible retries and it should be up to users of the library to address this.

You can use Erlang's logger_filter since Elixir v1.10 to filter error messages. If necessary, we can add more metadata to these errors to make it easier to identify them (although the :app key should be a good enough starting point). But I don't think we should discard them on behalf of the user.

Quick question: does the pipeline also fail when we get those errors? Or does it just log?

Thanks!

**Comment by SophisticaSean** [comment]
Right now, the receive_messages request failing means we don't pull messages on that pipeline run. 

I'm on board with logging retries but I'm not sure how best to go about letting users of the library to set/configure this.

Any direction you can point me in on how you'd like that configuration for retries to look? I think its non-optimal that we're losing a run to an erroneous 502 from Google so I would rather this library allow us to retry and let users configure that retry rather than Logging and waiting for the next run to receive new messages.

**Comment by SophisticaSean** [comment]
I would prefer us to `Logger.warn("Retrying :retrieve_messages request: retry count of #{retry_count}")` and then retry the request several times before logging it as a `Logger.error` considering this seems to be a common issue with pubsub at the moment.

**Comment by josevalim** [comment]
> Right now, the receive_messages request failing means we don't pull messages on that pipeline run.

Do you mean the pipeline as a whole crashes? If not, what do you mean by "pipeline run"?

> I would prefer us to Logger.warn("Retrying :retrieve_messages request: retry count of #{retry_count}")

I am still thinking about the details of how to implement backoff but I definitely think it is not our job as a library to decide which amount of failures is enough to be logged which ones are not. We should log always, include the retry as metadata, and allow you to filter it.

**Comment by SophisticaSean** [comment]
I've made the retry configurable and added retries to the other requests as well.

**Comment by SophisticaSean** [comment]
@josevalim Update: I have been using this in production for over a week now and it has effectively solved this issue. The 502's from Google are intermittent and unpredictable and the logic provided makes this library robust enough that the only errors and subsequent alerts we receive are actionable. This has effectively silenced these errors and has appropriately retried these requests when necessary.

**Comment by josevalim** [comment]
That’s great @SophisticaSean! Given this works, can we explore an option that is based on Tesla configuration as mentioned by @wojtekmach? Thanks!

**Comment by wojtekmach** [comment]
I think we could leverage retry that is built-in to Tesla, just a matter of setting the appropriate middleware _inside_ our library so the users won't have to do anything.

**Comment by wronfim** [comment]
Hey guys, I created a PR adding the @wojtekmach suggestion to use the Tesla retrier middleware. 
I was having the same problem described by @SophisticaSean. 
I'm running my solution in a dev environment at the moment, it's looking fine.
Let me know if I need to change or add anything.

**Comment by wojtekmach** [comment]
Closing in favour of #58
