### ISSUE TITLE
Getting checkout_timeout errors, hackney holding open connections indefinitely?

### ISSUE THREAD

**Issue by sorliem** [dashbitco/broadway_cloud_pub_sub#63]
Hello,

I am experiencing an issue where I am getting the `Unable to acknowledge messages with Cloud Pub/Sub, reason: :checkout_timeout` ([line](https://github.com/dashbitco/broadway_cloud_pub_sub/blob/4b907bea1c62360536f1f56628989cb2de393764/lib/broadway_cloud_pub_sub/google_api_client.ex#L161)) error logged around the same time I get pubsub expired deadline metrics recorded in GCP. 

My subscription does not get a lot of traffic and there is usually a message every 5-10 minutes most of the day, and maybe 1-2/minute during the peak times during the day. My pool options are the defaults (pool size = 2). 

I am curious why `recv_timeout` ([line](https://github.com/dashbitco/broadway_cloud_pub_sub/pull/20/files#diff-372f54ffad6f39b3b303346bc54adb52e8dd132c0deadf2911660979acb48edfR69)) was configured to be `:infinity`? Wouldn't that cause the request to block for 5 minutes in my case?

My theory is that because I have so few messages being processed, the moment a message is received from pubsub, the 2 connections in the pool are checked out trying to receive more messages, and then when that one message needs to be ack'd, there is no connection available to make an acknowledge request.

The one idea I had to fix this was to add `:middleware` option to override the recv_timeout: `[{Tesla.Middleware.Timeout, 4_000}]`. Is there any advice for configuring broadway_cloud_pub_sub for subscriptions that have a very low message publish rate?

Thank you!

Env:
elixir 1.10.4
erlang 22
broadway 0.6.2
broadway_cloud_pub_sub 0.6.0

**Comment by josevalim** [comment]
A PR that makes the value configurable is welcome. Although we should probably reduce the default to something that won’t invoke timeouts on Google’s API. Do you know if 5 minutes is the most on Google side? Or is it even less than that?

**Comment by mcrumm** [comment]
@josevalim @sorliem They don't publish an exact value, but anecdotally, without specifying `returnImmediately`, Google will close the connection after ~60s

**Comment by sorliem** [comment]
I might try and put up a PR to make it configurable. 

It seems like I'm experiencing the same thing as a previous issue, #18. Since I don't set `returnImmediately: true` (which is now deprecated according to Google), the message gets "stuck" because all 2 connections are checked out trying to pull new messages and probably getting the connection closed at 60s. Does that seem accurate @mcrumm?

**Comment by mcrumm** [comment]
@sorliem Yes I am almost positive that is _the exact problem_ we faced as well, which led to the current hackney adapter implementation in this package. Ultimately you need a connection pool size large enough to handle message pulls + acknowledgements.

Right now the default pool size is 2 * producer concurrency. Generally speaking I would think that enough to cover the acknowledgements, but maybe we should include the batcher concurrency in there as well? It's a bit difficult to pick a specific number of connections because messages can be acknowledged anywhere in the pipeline.

**Comment by sorliem** [comment]
I'm not convinced that upping the pool size would solve this though. If I upped it to 20, then I'd still have 20 connections checked out for ~60s at a time, which _slightly_ increases the chance that the acknowledgement request in_queue would secure a connection... but it's still iffy.

What I am hoping to achieve with making `recv_timeout` configurable is that I can set it to 5s which forces all connections in the pool to be checked in/out more frequently so that the acknowledgement request has a much higher chance to secure a connection before the deadline expires.

**Comment by mcrumm** [comment]
Only the producer processes pull messages. Any of the other pipeline processes _may_ acknowledge messages, depending on how your topology is configured and/or whether you use Message.ack_immediately/1 in your pipeline.

So increasing the pool size does not mean that all connections will be blocked by (or even involved in) receiving messages.

**Comment by mcrumm** [comment]
To be clear, I am saying that pool size is separate from producer concurrency.

So if you have a pipeline a with 2 producer processes:

```elixir
Broadway.start_link(__MODULE__,
  name: __MODULE__,
  producer: [
    module: {BroadwayCloudPubSub.Producer, []},
    concurrency: 2
  ],
)
```

then by default BroadwayCloudPubSub will start a hackney pool with four (`2 * 2`) connection processes. Only the two producers will ever make requests to pull messages, so only two connections will be in use. There should be two connections still available for acknowledgement.
