### ISSUE TITLE
Upgrade GOTH to newer version

### ISSUE THREAD

**Issue by fuatto** [dashbitco/broadway_cloud_pub_sub#70]
I'm using the latest version of broadway_cloud_pub_sub (0.7) which is using goth <= 1.2 (I've tried 1.0, 1.1, 1.2) That don't support GenServer way like in goth 1.3, therefore I did follow the instruction which uses the `Goth.Token.for_scope({account,  scope}, sub \\ nil), below is what I received:

![image](https://user-images.githubusercontent.com/17435002/148642186-8f8b475e-984e-4582-8b23-e692866ef88c.png)

To the trace below I think that there would be something wrong in my service account config, I wanted to log out the further error message inside but I don't know the way (any suggestion on this?)
![image](https://user-images.githubusercontent.com/17435002/148642351-9d1db35d-46e0-4bd5-bbf2-2ca0e0cb1f51.png)

If not, an Upgrade of Goth to the >= 1.3 with the usage below would be perfect (just pass in the json key file and that's it)

```
defmodule MyApp.Application do
  use Application

  def start(_type, _args) do
    credentials = "GOOGLE_APPLICATION_CREDENTIALS_JSON" |> System.fetch_env!() |> Jason.decode!()
    source = {:service_account, credentials, []}

    children = [
      {Goth, name: MyApp.Goth, source: source}
    ]

    Supervisor.start_link(children, strategy: :one_for_one)
  end
end
```

Thanks in advance

**Comment by josevalim** [comment]
Hi @fuatto! We specify Goth ~> 1.0, which means it should pick up 1.3 if you do a `mix deps.update goth`? Have you tried that? Or do you mean that our code is incorrect?

**Comment by fuatto** [comment]
Wow, thanks for really fast response sir @josevalim !

Yes, I did try the `mix deps.update goth` it only picks up the goth 1.2, as below:

![image](https://user-images.githubusercontent.com/17435002/148657333-609d9432-dcb5-4d53-a3cb-0a442834f993.png)

I also try to explicitly set `goth ~> 1.3.0-rc.3` as mix suggests: 

![image](https://user-images.githubusercontent.com/17435002/148657564-06d03f61-c66e-4fab-9187-44f438c5f27e.png)

I got:

![image](https://user-images.githubusercontent.com/17435002/148657608-b63b81e0-401b-4e51-8bc3-77d2a3d8fa0a.png)

which leads me to a dead-end...

Again, just to be clear about the issue I have: 

1/ I have to use the goth <= 1.2 as the latest broadway pub-sub doesn't support goth 1.3... (or maybe there is a way to upgrade goth to 1.3 with the current broadway pub-sub version

2/ I'm able to use broadway pub-sub just fine with the default service account as the docs instruction that is to use the funcition `Goth.Token.for_scope(<scope>)` (as in the Custom token generator part in the [docs](https://github.com/peburrows/goth))

3/ My use case is that I want to use the specific service account, which is instructed in [goth 1.2 docs](https://hexdocs.pm/goth/1.2.0/Goth.Token.html#for_scope/2) by passing in the service account email, and the result is in the prev. comment => for this direction I want to know exactly what the error is to take further actions (maybe I should create an issue in goth, but this is a little bit absurd as in the new 1.3-* versions, they just receive the whole json key file to get which service account is being used - so convenient already) -> any suggestion on this would also be appreciated! 🙏

**Comment by josevalim** [comment]
You can try as the error message says and specify `{:goth, "~> 1.3.0-rc.3", override: true}`, and that will force the prerelease version.

**Comment by fuatto** [comment]
^ It works with the override option, thank you so much for the help!

For others, I'm just not sure why I can't use the old way of goth <= 1.2 which is using the `Goth.Token.for_scope({account, scope}, sub \\ nil)` for broadway pub-sub ver 0.7 so if the use case is to use pubsub with specific account, just update goth   .
