### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by joladev** [dashbitco/broadway_cloud_pub_sub#89]
Is there a plan to add telemetry? Would a PR be welcome?

At a minimum I'm thinking of a span style event for the pull requests, with start and stop. For metadata I'd like to add the number of messages requested, maybe total demand too? This is something you have 0 insight into today using the library, and would be helpful for tweaking in production

**Comment by josevalim** [comment]
Yes, a pull request is welcome! We already emit telemetry events on both sqs and rabbitmq!
